version: 1
services:
  - type: web
    name: phonebook-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      NODE_ENV: production
    autoDeploy: true