### Get all persons
GET http://localhost:3001/api/persons

### Get phonebook info
GET http://localhost:3001/info

### Get person by ID
GET http://localhost:3001/api/persons/1

### Add a new person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "John Doe",
  "number": "123-456-7890"
}

### Try to add person with missing name (should 400)
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "555-0000"
}

### Try to add duplicate name (should 400)
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Damai gai",
  "number": "0797802208"
}

### Delete person with ID 1
DELETE http://localhost:3001/api/persons/1

### Delete non-existent person
DELETE http://localhost:3001/api/persons/999

### Get all persons after changes
GET http://localhost:3001/api/persons
